stages:
  - deploy

deploy-job:
  tags:
    - site
  stage: deploy
  script: docker build -t my_app . && docker run -d --name nuxt_app -p 5000:5000 my_app-f & docker container stop nuxt_app & docker container rm nuxt_app & docker build -t my_app . && docker run -d --name nuxt_app -p 5000:5000 my_app
